name: Static Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate Docker with GitHub Container Registry
        run: docker login --username cyberflaneurx --password ${{ secrets.GH_PAT }} ghcr.io

      - name: Pull Docker image
        run: docker pull ghcr.io/cyberflaneurx/plc-next-ghcr:latest

      - name: Run Cppcheck
        run: |
          docker run --rm -v $(pwd):/workspace -w /workspace ghcr.io/cyberflaneurx/plc-next-ghcr:latest /bin/bash -c "
          cppcheck --enable=all --inconclusive --error-exitcode=1 --suppress=unusedFunction .
          "
      - name: Build PLCNext Project
        run: |
          export BUILD_TYPE=Release
          PROJECT_NAME="StarterKit"  # Replace with the actual project name or pass as input
          echo "Build PLCNext release project for project $PROJECT_NAME"
          cd src/projects/$PROJECT_NAME
          plcncli generate code --verbose
          plcncli generate config --verbose
          plcncli build --verbose
