name: Static Code Analysis and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate Docker with GitHub Container Registry
        run: docker login --username cyberflaneurx --password ${{ secrets.GH_PAT }} ghcr.io

      - name: Pull Docker image
        run: docker pull ghcr.io/cyberflaneurx/plc-next-ghcr:latest

      - name: Start Docker Container
        run: |
          docker run -d --name cppcheck_container -v $(pwd):/code -w /code ghcr.io/cyberflaneurx/plc-next-ghcr:latest sleep infinity

      - name: Run Cppcheck inside Container
        run: |
          docker exec -i -w /code --user sun cppcheck_container cppcheck --quiet --enable=warning --force --error-exitcode=2 -i src/projects

      - name: List Directory Contents (Optional, for Debugging)
        run: |
          docker exec -i -w /code/src/projects/StarterKit --env BUILD_TYPE=Release --user sun cppcheck_container ls -alh

      - name: Generate PLCNext Code inside Container
        run: |
          docker exec -i -w /code/src/projects/StarterKit --env BUILD_TYPE=Release --user sun cppcheck_container plcncli generate code --verbose

      - name: Generate PLCNext Config inside Container
        run: |
          docker exec -i -w /code/src/projects/StarterKit --env BUILD_TYPE=Release --user sun cppcheck_container plcncli generate config --verbose

      - name: Build PLCNext Project inside Container
        run: |
          docker exec -i -w /code/src/projects/StarterKit --env BUILD_TYPE=Release --user sun cppcheck_container plcncli build --verbose

      - name: Deploy PLCNext Project inside Container
        run: |
          docker exec -i -w /code/src/projects/StarterKit --env BUILD_TYPE=Release --user sun cppcheck_container plcncli deploy

      - name: Stop Docker Container
        run: docker stop cppcheck_container

      - name: Remove Docker Container
        run: docker rm cppcheck_container
